### PR TITLE
Finish a complete render to .html files

### PR DESCRIPTION
**Pull request by cameronjroe**

### CODE REVIEW

**Comment by ismay** [comment]
Thanks for the pr. Although I think that this would be best left to [metalsmith-rename](https://github.com/MoOx/metalsmith-rename). What are your reasons for wanting to include this in metalsmith-in-place instead of using metalsmith-rename?

**Comment by cameronjroe** [comment]
The files are getting rendered so I think it's the responsibility of the rendering to convert to convert the file names. If they're getting copied by metalsmith to the destination, leaving a remaining `.liquid` or `.hbs` doesn't really make sense. `metalsmith-rename` seems like more of a utility than a dependency for this type of operation.

**Comment by ismay** [comment]
Yeah that makes sense. Reason I was suggesting metalsmith-rename is because [metalsmith tries to keep with the unix philosophy](https://github.com/metalsmith/metalsmith/issues/153#issuecomment-123385449), so I'm trying to keep this plugin as simple as possible.

Instead of always renaming to .html we could also make the renaming optional/configurable (where you could opt out of renaming or change the extension for example). I can't really imagine a scenario where someone wouldn't want to rename to .html, but maybe there is one we haven't thought of yet? What do you think?

**Comment by cameronjroe** [comment]
Yeah, don't get me wrong I love the separation of concerns principle and following a unix-like philosophy, but I think this isn't really a case where that makes sense. I agree with you that I can't think of a use case where you wouldn't want to create .html file if you're rendering a template. Isn't that the point of rendering it from it's original extension. The contents get transformed to html so technically the file is an .html file.

**Comment by ismay** [comment]
Ok, sounds good. Two questions: 

* Did you check why the tests are failing?
* This won't work for files with multiple extensions, can you think of an elegant way to handle that as well?

**Comment by cameronjroe** [comment]
Sure, I'll look into those.

**Comment by ismay** [comment]
Cool, thanks :+1:

**Comment by ismay** [comment]
Hey @cameronjroe Any luck with testing and the multiple extension problem?

**Comment by cameronjroe** [comment]
Not sure what you mean by multiple extensions. Like `.coffee.md`? Wouldn't someone just use a `.coffee` extension?

**Comment by ismay** [comment]
See here: https://github.com/superwolff/metalsmith-layouts/issues/46

**Comment by ismay** [comment]
But maybe it's safe to assume that there's no reason to use multiple extensions. I can't think of one at least.

**Comment by ismay** [comment]
API

By the way, I did find one problem with always renaming to `.html`. If people are processing markdown, currently they can just chain the metalsmith-markdown plugin after metalsmith-in-place. Files will keep their `.md` extension and be renamed by metalsmith-markdown to `.html`.

This will break if we always rename to `.html`. I think the best solution would be to accept a flag `rename`, that'll be set to `true` by default. If turned off the extension won't be touched. It will be a breaking change, but at least people can opt out.

Multiple extensions

Also, regarding the multiple extensions. It might be related to [this](http://stackoverflow.com/a/31739350/4210742), where it is meant to denote: `[filename].[format].[builder]` and is usually used for rails templates. As this isn't a rails tool I think we can safely ignore that practice. Because replacing all extensions might cause new problems for files with dots in their names.

**Comment by cameronjroe** [comment]
I've added a rename option. Not sure why checks fail, but I removed the `--harmony-generators` because it was throwing a weird error. Tests pass when I removed it.

**Comment by ismay** [comment]
Tests are failing on travis because it's still testing with node 0.12 (which needed the `--harmony-generators` flag for testing with metalsmith 2.x). If you change [this line](https://github.com/superwolff/metalsmith-in-place/blob/master/.travis.yml#L4) to `"node"`, it'll pick the latest stable node version and tests should be succeeding on travis as well.

**Comment by cameronjroe** [comment]
Okay, looks like that worked. Thanks.

**Comment by ismay** [comment]
Cool, thanks for the pr!

**Comment by ismay** [comment]
Published on npm as 1.4.3

**Pull request merged**
